### ISSUE TITLE
pre-trained dcgan is not found.

### ISSUE THREAD

**Issue by yukuner** [sunghbae/dcgan-matconvnet#1]
Pre-trained dcgan is not found in https://www.dropbox.com/s/fvasd83oqgse7xr/net_dcgan.mat?dl=0.
maybe there is some mistake.

**Comment by Adarine99** [comment]
I can't find the Pre-trained dcgan neither,hope you can reload it.Thank you very much!!!

**Comment by yukuner** [comment]
https://www.dropbox.com/s/dmyqd6yfga9wsm6/net_dcgan.mat?dl=0
I hope it can help you. Maybe vpn is needed.

**Comment by sunghbae** [comment]
Thanks @yukuner for replying. I corrected it in the README file.
