### ISSUE TITLE
Other dataset

### ISSUE THREAD

**Issue by mab85** [sunghbae/dcgan-matconvnet#4]
How to adapt the code to work for own data not celeba dataset

**Comment by maryam089** [comment]
Change the datasets in the folders ... and remove every file  in the folder where training epochs are saved

**Comment by maryam089** [comment]
Now comment the test part 
In the main file... train the network then copy the 300 epoch file in net folder and uncoment the testing part... click run .. it will generate new images according to the training u did

**Comment by mab85** [comment]
@maryam089 it have error "error in main_start_dcgan (line 56) get_train_DCGAN(opts.train);

**Comment by maryam089** [comment]
did you change the name of the file ? net-epoch-300 to net_dcgan in the net folder ?

**Comment by mab85** [comment]
@maryam089 Thank you now it run, but if i want to access the all features of discriminator until the 4 × 4 spatial grid how to make it.

**Comment by maryam089** [comment]
Welcome... unfortunately i don't know either :(
