### ISSUE TITLE
Access Features

### ISSUE THREAD

**Issue by mab85** [sunghbae/dcgan-matconvnet#5]
@sunghbae  How to access Features of discriminator?. I mean if i want to see the feature of every image created by discriminator, how?.

**Comment by sunghbae** [comment]
Hi @mab85 , I guess you want to see the output values of a convolution layer (called features) in Discrminator.

If so, you can set a breaking point at line 11 in "/matconvnet-1.0-beta24/matlab/+dagnn/Conv.m" and run "get_test_DCGAN.m" (press F5).

The variable "output{1}" in Conv.m is the output of the convolution layer.

**Comment by mab85** [comment]
@**sunghbae** Thanks for reply, but i want to see the features from all layers until the layer "**% 8x8 to 4x4**"
in discriminator part in "**main_start_dcgan.m**" for every image in data folder not in "**test_img_DCGAN**"

**Comment by sunghbae** [comment]
@mab85 That's the same manner. You can run "main_start_dcgan.m" after setting the break point at line 11 in "/matconvnet-1.0-beta24/matlab/+dagnn/Conv.m".

And see "output{1}" in "Conv.m" for the convolution layers that you are focusing on.

**Comment by mab85** [comment]
@sunghbae Thanks for your reply, which part of code take image by image from data folder and passed it to discriminator network. for the last answer it is difficult to use debug by step for data exceed 200,000 to see features @sunghbae

**Comment by mab85** [comment]
@sunghbae i just want to know how the output of one epoch be equal to all dataset samples?. From my knowledge that one epoch must run on all dataset so, if i use your answer withe break point , it save 16 outputs for each batch in epoch so, one epoch have 160 outputs.

**Comment by luma-alharbawee** [comment]
I have read your reply about the question"How to access Features of discriminator ". 
Is that possible to provide more clarifications please about how to get the features from the discriminator of the input images as steps in matlab.
